/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ecomm;

/**
 *
 * @author Rohan
 */
public class Payment1 extends javax.swing.JFrame {


    /**
     * Creates new form payment
     */
    public Payment1() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        r3 = new javax.swing.JRadioButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        r4 = new javax.swing.JRadioButton();
        r5 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 750));
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(153, 0, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fs.jpg"))); // NOI18N
        jButton1.setText("MOBILE ACCESSORIES");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 0, 1370, 80);

        r1.setBackground(new java.awt.Color(255, 255, 51));
        buttonGroup1.add(r1);
        r1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        r1.setText("CREDIT  CARD");
        r1.setIconTextGap(20);
        getContentPane().add(r1);
        r1.setBounds(110, 150, 260, 25);

        r2.setBackground(new java.awt.Color(255, 255, 0));
        buttonGroup1.add(r2);
        r2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        r2.setText("DEBIT  CARD");
        r2.setIconTextGap(20);
        getContentPane().add(r2);
        r2.setBounds(110, 250, 260, 25);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT  YOUR  BANK", "STATE BANK OF INDIA", "BANK OF INDIA", "CANARA BANK", "HDFC BANK", "BANK OF BARODA", "CENTRAL BANK" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(140, 290, 210, 30);

        r3.setBackground(new java.awt.Color(255, 255, 0));
        buttonGroup1.add(r3);
        r3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        r3.setText("NET BANKING");
        r3.setIconTextGap(20);
        getContentPane().add(r3);
        r3.setBounds(110, 380, 260, 30);

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT  YOUR  BANK", "STATE BANK OF INDIA", "BANK OF INDIA", "CANARA BANK", "HDFC BANK", "BANK OF BARODA", "CENTRAL BANK" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(140, 440, 210, 30);

        r4.setBackground(new java.awt.Color(255, 255, 0));
        buttonGroup1.add(r4);
        r4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        r4.setText("CASH ON DELIVERY");
        r4.setIconTextGap(20);
        getContentPane().add(r4);
        r4.setBounds(110, 520, 360, 30);

        r5.setBackground(new java.awt.Color(255, 255, 0));
        buttonGroup1.add(r5);
        r5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        r5.setText("PAYTM");
        r5.setIconTextGap(20);
        getContentPane().add(r5);
        r5.setBounds(113, 620, 260, 30);

        jButton2.setBackground(new java.awt.Color(51, 255, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("CONTINUE >>");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(930, 620, 220, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ecomm.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1370, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         CompanyHome c = new CompanyHome();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        if(r1.isSelected())
        {
         CreditDebit c = new CreditDebit();
         c.setVisible(true);
         this.dispose();   
        }
        if(r2.isSelected()){
         CreditDebit c = new CreditDebit();
         c.setVisible(true);
         this.dispose(); 
        }
        if(r3.isSelected()){
         Netbanking c = new Netbanking();
         c.setVisible(true);
         this.dispose();
        }
        if(r4.isSelected()){
          Billing b = new Billing();
          b.setVisible(true);
          this.dispose();
        }
        if(r5.isSelected()){
         Paytm c = new Paytm();
         c.setVisible(true);
         this.dispose();  
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JRadioButton r4;
    private javax.swing.JRadioButton r5;
    // End of variables declaration//GEN-END:variables
}
