package ecomm;


import ecomm.CompanyHome;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LENOVO-PC
 */
public class SamsungGuard1 extends javax.swing.JFrame {

static String product;
static int price;
static int ca;
    /**
     * Creates new form SGuard
     */
    public SamsungGuard1() {
        initComponents();
    }
    public SamsungGuard1(String m,int n,int o) {
        
        product = m;
        price = n;
        ca = o;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bb1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        l4 = new javax.swing.JLabel();
        b4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        b5 = new javax.swing.JButton();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 750));
        getContentPane().setLayout(null);

        bb1.setBackground(new java.awt.Color(204, 204, 204));
        bb1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        bb1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fs.jpg"))); // NOI18N
        bb1.setText("MOBILE ACCESSORIES");
        bb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bb1ActionPerformed(evt);
            }
        });
        getContentPane().add(bb1);
        bb1.setBounds(240, 0, 810, 80);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a7glass.jpg"))); // NOI18N
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 90, 270, 220);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a5_1.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(370, 90, 222, 200);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/s4.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(730, 90, 230, 190);

        b1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b1.setText("ADD TO CART");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(20, 330, 240, 50);

        b2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b2.setText("ADD TO CART");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2);
        b2.setBounds(370, 330, 240, 50);

        b3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b3.setText("ADD TO CART");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3);
        b3.setBounds(720, 330, 240, 50);

        l4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/s5_1.jpg"))); // NOI18N
        getContentPane().add(l4);
        l4.setBounds(10, 390, 250, 220);

        b4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b4.setText("ADD TO CART");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        getContentPane().add(b4);
        b4.setBounds(10, 630, 240, 50);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/s3.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(490, 390, 230, 210);

        b5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b5.setText("ADD TO CART");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        getContentPane().add(b5);
        b5.setBounds(490, 620, 240, 50);

        l1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        l1.setText("Galaxy A7 @99");
        getContentPane().add(l1);
        l1.setBounds(90, 310, 120, 15);

        l2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        l2.setText("Galaxy A5 @99");
        getContentPane().add(l2);
        l2.setBounds(450, 310, 110, 15);

        l3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        l3.setText("S4 @99");
        getContentPane().add(l3);
        l3.setBounds(790, 300, 60, 15);

        l6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        l6.setText("S5 @99");
        getContentPane().add(l6);
        l6.setBounds(120, 610, 60, 15);

        l5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        l5.setText("S3 @99");
        getContentPane().add(l5);
        l5.setBounds(590, 600, 46, 15);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ecomm.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1370, 880);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bb1ActionPerformed
        // TODO add your handling code here:
         CompanyHome c = new CompanyHome();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bb1ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        String f = l1.getText();
        int g = 99;
        
        SamsungGuard1 b = new SamsungGuard1(f,g,5);
        Payment p = new Payment();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        String f = l2.getText();
        int g = 99;
        
        SamsungGuard1 b = new SamsungGuard1(f,g,5);
        Payment p = new Payment();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        String f = l3.getText();
        int g = 99;
        
        SamsungGuard1 b = new SamsungGuard1(f,g,5);
        Payment p = new Payment();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
        String f = l6.getText();
        int g = 99;
        
        SamsungGuard1 b = new SamsungGuard1(f,g,5);
        Payment p = new Payment();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
        String f = l5.getText();
        int g = 99;
        
        SamsungGuard1 b = new SamsungGuard1(f,g,5);
        Payment p = new Payment();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_b5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SamsungGuard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SamsungGuard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SamsungGuard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SamsungGuard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SamsungGuard1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton bb1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    // End of variables declaration//GEN-END:variables
}
