package ecomm;


import ecomm.CompanyHome;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LENOVO-PC
 */
public class UserHome1 extends javax.swing.JFrame {
//static String name;
//static String pass;
static String spec;
    /**
     * Creates new form Home
     */
    public UserHome1() {
        initComponents();
    }
    public UserHome1(String z) {
         //name = x;
         //pass = y;
         spec = z;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l2 = new javax.swing.JLabel();
        cb1 = new javax.swing.JComboBox<>();
        cb2 = new javax.swing.JComboBox<>();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        cb3 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 750));
        setPreferredSize(new java.awt.Dimension(1000, 1000));
        getContentPane().setLayout(null);

        l2.setBackground(new java.awt.Color(255, 51, 102));
        l2.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        l2.setText("OUR PRODUCTS");
        getContentPane().add(l2);
        l2.setBounds(310, 90, 320, 34);

        cb1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Samsung", "Apple" }));
        getContentPane().add(cb1);
        cb1.setBounds(270, 320, 100, 21);

        cb2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cb2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Samsung", "Apple" }));
        getContentPane().add(cb2);
        cb2.setBounds(750, 410, 100, 21);

        l3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l3.setText("Glass Guards");
        getContentPane().add(l3);
        l3.setBounds(260, 280, 150, 22);

        l4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l4.setText("USB Cables");
        getContentPane().add(l4);
        l4.setBounds(750, 380, 110, 20);

        l5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l5.setText("Back Cases");
        getContentPane().add(l5);
        l5.setBounds(310, 520, 140, 22);

        cb3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cb3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Samsung", "Apple" }));
        getContentPane().add(cb3);
        cb3.setBounds(310, 550, 110, 21);

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fs.jpg"))); // NOI18N
        jButton2.setText("MOBILE ACCESSORIES");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(0, 0, 1370, 80);

        b1.setBackground(new java.awt.Color(255, 255, 102));
        b1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b1.setText("MY  TRANSACTION  HISTORY");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(970, 120, 270, 60);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/download.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 100, 210, 180);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usb.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(650, 190, 240, 180);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cases.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 400, 300, 300);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("VIEW  SELECTED  PRODUCT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(780, 570, 330, 50);

        jButton3.setBackground(new java.awt.Color(255, 255, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("MY  ACCOUNTS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(970, 260, 270, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ecomm.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1350, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        usertrans u1 = new usertrans();
        u1.setVisible(true);
        this.dispose();       
    }//GEN-LAST:event_b1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         CompanyHome c = new CompanyHome();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         String glass = cb1.getSelectedItem().toString();
         String cable = cb2.getSelectedItem().toString();
         String cases = cb3.getSelectedItem().toString();
         if(glass.equalsIgnoreCase("Samsung")){
              String s = "Glass Guard";
              //Login l = new Login();
              //this.name = l.name;
              //this.pass = l.pass;
              UserHome1 u = new UserHome1(s);
              SamsungGuard1 s1 = new SamsungGuard1();
              s1.setVisible(true);
              this.dispose();
         }else if(glass.equalsIgnoreCase("Apple")){
             String s = "Glass Guard";
              
              UserHome1 u = new UserHome1(s);
              AppleTemperd s2 = new AppleTemperd();
              s2.setVisible(true);
              this.dispose(); 
         }else if(cable.equalsIgnoreCase("Samsung")){
             String s = "USB Cable";
              
              UserHome1 u = new UserHome1(s);
            SamsungUsb s3 = new SamsungUsb();
             s3.setVisible(true);
             this.dispose(); 
         }else if(cable.equalsIgnoreCase("Apple")){
             String s = "USB Cable";
              
              UserHome1 u = new UserHome1(s);
             AppleUsb s4 = new AppleUsb();
             s4.setVisible(true);
             this.dispose();    
         }else if(cases.equalsIgnoreCase("Samsung")){
              String s = "Back Cover";
     
              
              UserHome1 u = new UserHome1(s);
             SamsungBack s5 = new SamsungBack();
             s5.setVisible(true);
             this.dispose();  
         }else if(cases.equalsIgnoreCase("Apple")){
             String s = "Back Cover";
              UserHome1 u = new UserHome1(s);
             AppleBack s6 = new AppleBack();
             s6.setVisible(true);
             this.dispose();   
         }
             
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       useraccounts u1 = new useraccounts();
       u1.setVisible(true);
       this.dispose(); 
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserHome1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JComboBox<String> cb2;
    private javax.swing.JComboBox<String> cb3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    // End of variables declaration//GEN-END:variables
}
