/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ecomm;

import java.sql.*;
import javax.swing.*;

/**
 *
 * @author HP
 */
public class UserSignin extends javax.swing.JFrame {

    /**
     * Creates new form Sign_up
     */
    public UserSignin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 750));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FILL FORM TO SIGN UP");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(340, 30, 440, 40);

        l1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        l1.setText("USERNAME:");
        getContentPane().add(l1);
        l1.setBounds(210, 100, 143, 31);

        l4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        l4.setText("PASSWORD:");
        getContentPane().add(l4);
        l4.setBounds(210, 280, 143, 34);

        l2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        l2.setText("GENDER:");
        getContentPane().add(l2);
        l2.setBounds(210, 160, 143, 39);

        l3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        l3.setText("MOBILE NUMBER:");
        getContentPane().add(l3);
        l3.setBounds(210, 220, 230, 32);

        t1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(t1);
        t1.setBounds(620, 100, 229, 28);

        buttonGroup1.add(r1);
        r1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        r1.setText("MALE");
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });
        getContentPane().add(r1);
        r1.setBounds(610, 170, 100, 37);

        buttonGroup1.add(r2);
        r2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        r2.setText("FEMALE");
        getContentPane().add(r2);
        r2.setBounds(810, 170, 120, 37);

        t2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(t2);
        t2.setBounds(620, 220, 229, 32);

        t3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(t3);
        t3.setBounds(620, 290, 229, 34);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("CLICK  HERE  TO SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(470, 560, 240, 41);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("CONFIRM PASSWORD:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(210, 360, 280, 27);

        t4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(t4);
        t4.setBounds(620, 360, 229, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("SECURITY QUESTION:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(210, 430, 270, 29);

        t5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        t5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t5ActionPerformed(evt);
            }
        });
        getContentPane().add(t5);
        t5.setBounds(620, 480, 230, 29);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("which is your favourite animal??");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(220, 480, 290, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("BACK  TO  HOME  ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(120, 640, 220, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       String n = t1.getText();
       String p = t3.getText();
       String m = t2.getText();
       String s = t5.getText();
       String cp = t4.getText();
       String g = "";
        if(r1.isSelected())
        {
            g = r1.getText();
        }
        if(r2.isSelected()){
            g = r2.getText(); 
        }
        try{
             Class.forName("oracle.jdbc.driver.OracleDriver"); 
             Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","Rohan", "Rohan");
           PreparedStatement pst = con.prepareStatement("Insert into CUSTOMER values(?,?,?,?,?)");
           pst.setString(1,n);
           if(cp.equals(p)){
               
           pst.setString(2,p);
           
           }else{
               
             JOptionPane.showMessageDialog(this,"PASSWORD NOT MATCHING"); 
             
           }
           pst.setString(3,g);
           pst.setString(4,m);
           pst.setString(5,s);
           int x = pst.executeUpdate();
           if (x>0)
            {
              JOptionPane.showMessageDialog(this,"SUCCESSFULLY SIGNED UP.........");
            }
            else {
               JOptionPane.showMessageDialog(this,"ERROR......");
            }
           con.close();
          
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e);
            }
        Login l = new Login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void t5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CompanyHome c = new CompanyHome();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserSignin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserSignin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserSignin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserSignin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserSignin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    // End of variables declaration//GEN-END:variables
}
